language: ruby
script: bundle exec rspec spec
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
gemfile:
  - spec/gemfiles/Gemfile.rails-3.2.x
  - spec/gemfiles/Gemfile.rails-4.0.x
  - spec/gemfiles/Gemfile.rails-4.1.x
matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: spec/gemfiles/rails-4.1.x.gemfile
  allow_failures:
    - gemfile: spec/gemfiles/rails-4.1.x.gemfile
  fast_finish: true
