language: ruby
rvm:
  - 1.9.3
  - 2.0.0
env:
  - DB=postgresql
  - DB=postgresql RAILS_VERSION=4.0.0 SASS_VERSION=4.0.0
before_script:
  - psql -c 'create database recurring_select_test' -U postgres
script:
  - rspec spec
